source 'https://git.epam.com/anton_babich/podspec.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '9.0'

target 'Library2_Example' do
  use_frameworks!

#  pod 'Library2', :path => '../'
  pod 'Library2'
#  pod 'Library1'
#  pod 'Library1', :path => '../../Library1/'

end
